# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Download File
        run: wget -O aosp_arm64-symbols-15212407.zip "https://storage.googleapis.com/android-build/builds/aosp-android13-gsi-linux-aosp_arm64-userdebug/15212407/dc856a504e7f698de7f504aa385c3cdd0b8b3ad7473694f0500df54d744617c6/1/aosp_arm64-symbols-15212407.zip?GoogleAccessId=gcs-sign%40android-builds-project.google.com.iam.gserviceaccount.com&Expires=1777721626&Signature=RSMAoSJajSJGL6DYlQxaZBzO3YOICsn1XgCI5mlHa3WEiEG0qlni5L06mI48733UJdHZF6Vdtdh61wz7CmeHkpENGcX9wmjR0Xmon7Yknp%2B6eh%2B6WAqRSi3o%2FDZepYo7leZLdlDN8ufIZewxZeXsjQ5vuVZ%2FgcP0KFQLc6xjxVHYhIBBvmeELb7Ch7JAEFveb3yqsW6dG%2FU1pJeo9hYkhYQeQi9XDaaayq3gTt8kGPaYu%2BNoN9dPD6ju8tc%2BFbjc9B3HW%2B1Jq5GhEqYy7i1GdO5RACeyuDG1xpLr4W3cYILqUIRL%2FufD%2BbqXecgluhgJXEIHO3CAoSlfXmaEjVg9Pg%3D%3D&response-content-disposition=attachment"
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: File Download
          name: File
          draft: false
          prerelease: false
          files: aosp_arm64-symbols-15212407.zip
